/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;
import DataBaseConnector.sqlConnector;
import admin.admin;

/**
 *
 * @author Ruwan Bandara
 */
public class studentLogin extends javax.swing.JFrame {

    /**
     * Creates new form studentLogin
     */
    public studentLogin() {
        super("studentLogin");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLStudentId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ui_StudentId = new javax.swing.JTextField();
        ui_Password = new javax.swing.JPasswordField();
        ui_Login = new javax.swing.JButton();
        ui_Cancel = new javax.swing.JButton();
        ui_u = new javax.swing.JLabel();
        ui_p = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Login Form");

        jLStudentId.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLStudentId.setText("Student Id : ");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Password  :");

        ui_StudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_StudentIdActionPerformed(evt);
            }
        });

        ui_Login.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ui_Login.setText("Login");
        ui_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_LoginActionPerformed(evt);
            }
        });

        ui_Cancel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ui_Cancel.setText("Cancel");
        ui_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ui_CancelActionPerformed(evt);
            }
        });

        ui_u.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ui_u.setForeground(new java.awt.Color(255, 0, 0));
        ui_u.setText("*");

        ui_p.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ui_p.setForeground(new java.awt.Color(255, 0, 0));
        ui_p.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStudentId)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ui_Cancel)
                                .addGap(152, 152, 152)
                                .addComponent(ui_Login))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ui_StudentId, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                                    .addComponent(ui_Password))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ui_p, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ui_u, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ui_StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ui_u)
                            .addComponent(jLStudentId))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ui_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(ui_p))
                .addGap(103, 103, 103)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ui_Login)
                    .addComponent(ui_Cancel))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(938, 691));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ui_StudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_StudentIdActionPerformed

    }//GEN-LAST:event_ui_StudentIdActionPerformed

    private void ui_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_LoginActionPerformed
        ui_u.setVisible(false);
        ui_p.setVisible(false);

        if(ui_StudentId.getText().equals(""))
        {
            ui_u.setVisible(true);
        }if(String.valueOf(ui_Password.getPassword()).equals(""))
        {
            ui_p.setVisible(true);
        }
        else{
//            Connection con = dbConnector.getConnection();
//            PreparedStatement ps;

//            try {
         
                
                String id = ui_StudentId.getText();
                String password = String.valueOf(ui_Password.getPassword());
                
                admin admin = new admin();
                boolean test= admin.adminLogin(id, password);
                
                if (test) {
                                        
                     setVisible(false);
                    int total = admin.countData();
                    System.out.println(total);
                    
                     home Home = new home();
                     Home.setVisible(true);
                     Home.pack();
                     Home.setLocationRelativeTo(null);
                     Home.setExtendedState(JFrame.MAXIMIZED_BOTH);
                     home.jLWelcome.setText("Welcome <"+ui_StudentId.getText()+">");
                     this.dispose();
                     
                    
                }else {
                    System.out.println("wrong");
                }
                
                
               
                

//                
//
//                if(rs.next()){
//                    

//                }else{
//                    System.out.println("NO");
//                }
//
//            } catch (SQLException ex) {
////                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
//                    JOptionPane.showMessageDialog(null, ex);
//            }

        }

    }//GEN-LAST:event_ui_LoginActionPerformed

    private void ui_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ui_CancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ui_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLStudentId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ui_Cancel;
    private javax.swing.JButton ui_Login;
    private javax.swing.JPasswordField ui_Password;
    private javax.swing.JTextField ui_StudentId;
    private javax.swing.JLabel ui_p;
    private javax.swing.JLabel ui_u;
    // End of variables declaration//GEN-END:variables
}
